#- name: Update machine
 # hosts: all
 # action: sudo apt update
 # ignore_errors: yes

//---
#- hosts: all
 # become: yes
  #become_method: sudo
  #tasks:
#- name: "Update cache & Full system update"
  #apt:
  #update_cache: true
  #upgrade: dist
 # cache_valid_time: 3600
#  force_apt_get: true

- name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
